name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip openjdk-11-jdk git zip unzip
          pip install buildozer
          pip install cython==0.29.36

      - name: Accept Android Licenses
        run: |
          mkdir -p ~/.android && touch ~/.android/repositories.cfg
          yes | sdkmanager --licenses || true
          sdkmanager "build-tools;36.0.0-rc3"

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: PolygonAreaCalc
          path: bin/*.apk
