name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip openjdk-11-jdk git zip unzip wget
          pip install buildozer
          pip install cython==0.29.36

      - name: Install Android Command-Line Tools
        run: |
          mkdir -p $HOME/.buildozer/android/platform
          cd $HOME/.buildozer/android/platform
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O tools.zip
          unzip tools.zip -d cmdline-tools
          mv cmdline-tools/cmdline-tools $HOME/.buildozer/android/platform/cmdline-tools
          rm -rf cmdline-tools tools.zip
          export ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH
          yes | sdkmanager --licenses || true
          sdkmanager "build-tools;36.0.0-rc3"

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: PolygonAreaCalc
          path: bin/*.apk
